[project]
name = "lecture3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crypto>=1.4.1",
    "pwn>=1.0",
    "setproctitle>=1.3.7",
    "utils>=1.0.2",
]
